title: Beauty. Body. Bliss
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8512127
  brandStrength: 0.540112
  lightness: 0
  brandColors:
    - '#EBF4F4'
    - '#8EBDA3'
    - '#CC181E'
    - '#F7CAAD'
    - '#76624E'
  rhythmicContrast: 0.04617537
typography_spectrum: 0.4657940692268312
description: why not have it all?
layout_spectrum: 0.2882463
name: fabfitfree
