layout_spectrum: 0.4357912465929985
typography_spectrum: 0.5450751257594675
color:
  saturation: 0.015483923023566604
  brandStrength: 0.812454337021336
  lightness: 0.699611545773223
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  rhythmicContrast: 0.1600657047238201
title: Beauty. Body. Bliss
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: why not have it all?
name: fabfitfree
