typography_spectrum: 0.5115701616741717
color:
  saturation: 0.015483923023566604
  brandStrength: 0.812454337021336
  lightness: 0.699611545773223
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  rhythmicContrast: 0.1600657047238201
layout_spectrum: 0.4357912465929985
author:
  name: g
  email: g@fabfitfree.com
  url: 'http://www.facebook.com/gayanna'
name: fabfitfree
navigation:
  - name: Products
    url: 'http://justthrive.isagenix.com/en-US/IsaProduct/IsaProduct'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Beauty. Body. Bliss
description: why not have it all?
