title: Beauty. Body. Bliss
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8512127
  brandStrength: 0.866138
  lightness: 0
  brandColors:
    - '#FFFFFF'
    - '#505048'
    - '#000000'
    - '#64748B'
    - '#A9B2C1'
  rhythmicContrast: 0.04617537
typography_spectrum: 0.5466418
description: why not have it all?
layout_spectrum: 0
name: fabfitfree
