layout_spectrum: 0.606566206177715
typography_spectrum: 0.2554565970025182
color:
  saturation: 0.010512633479596807
  brandStrength: 0.8154932624184629
  rhythmicContrast: 0.16222131149557484
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  lightness: 0.6540312022325758
coverPrefs:
  filter: false
author:
  name: g
  email: g@fabfitfree.com
  url: 'http://www.facebook.com/gayanna'
title: Beauty. Body. Bliss
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: your best you. your best life.
navigation:
  - name: Products
    url: 'http://justthrive.isagenix.com/en-US/IsaProduct/IsaProduct'
    type: external
  - name: Transformations are for Every Body
    url: >-
      http://justthrive.isagenix.com/en-US/Isamovie#cat=weightLoss&vid=Pg6gF3DPt8k&useBc=0
    type: external
  - name: Team Isagenix
    url: 'http://justthrive.isagenix.com/en-us/people/team-isagenix/team-isagenix'
    type: external
  - name: Start Your Life
    url: 'http://www.startyourlife.com/'
    type: external
  - name: Heathy Mind + Body
    url: 'http://healthymindandbody.com/'
    type: external
  - name: Breakthrough
    url: >-
      http://justthrive.isagenix.com/en-US/Isamovie#cat=wealthCreation&vid=M7sK2-SC8vk&useBc=0
    type: external
  - name: isaBody Challenge
    url: 'http://justthrive.isagenix.com/en-US/isabody-challenge'
    type: external
  - name: Disclaimers
    url: 'http://justthrive.isagenix.com/en-US/disclaimers'
    type: external
name: fabfitfree
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4474342-cef2-4182-b77d-2f5a163c83ef.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f4474342-cef2-4182-b77d-2f5a163c83ef.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
purpose:
  - type: contact
    url: 'mailto:g@fabfitfree.com'
    label: email g
  - type: external
    url: 'http://justthrive.isagenix.com'
    label: join our tribe
github: true
